version: '2'
services:
    dbscompetencyportal-app:
        image: dbscompetencyportal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://dbscompetencyportal-mariadb:3306/dbscompetencyportal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dbscompetencyportal-mariadb:
        extends:
            file: mariadb.yml
            service: dbscompetencyportal-mariadb
